### ISSUE TITLE
npm start doesn't automatically rebuild

### ISSUE THREAD

**Issue by devinmcmanus** [them-es/wordpress-blocks-boilerplate#1]
Hi there,
I'm trying to add a new block to a custom theme and for some reason I have to run `npm start` every time I make a change. Is this the intended behaviour?

Regards,
Devin M

**Comment by them-es** [comment]
@devinmcmanus That's not how it's supposed to work.

This boilerplate uses `wp-scripts` and as you can see here https://developer.wordpress.org/block-editor/getting-started/devenv/get-started-with-wp-scripts/#the-build-process-with-wp-scripts  the`npm run start` command rebuilds the source files whenever a change is detected.

Just tested it and it works as expected...
Could you try to remove the `build` directory and enter the command again?

**Comment by devinmcmanus** [comment]
Same issue after removing the `build` directory. I'm running Debian 11 on WSL. I ran into a similar issue using the them.es/starter-bootstrap theme and resolved it by making these changes:

Modify package.json
```
"scripts": {
  "watch": "webpack serve --progress && wp-scripts start",
  "build": "wp-scripts build"
},
```

Add these lines to webpack.config.js
```
watchOptions: {
  poll: true
},	
```

However, I may have resolved the issue here by creating a custom `webpack.config.js`

```
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

module.exports = {
    ...defaultConfig,
    module: {
        ...defaultConfig.module,
        rules: [
            ...defaultConfig.module.rules,
        ],
    },
    watchOptions: {
        poll: true
    },
};
```

**Comment by them-es** [comment]
Glad you got it resolved.

**For reference:** According to the webpack documentation the `poll` parameter may be required in virtual environments to keep CPU usage minimal:

https://webpack.js.org/configuration/watch/#watchoptionspoll 
> If watching does not work for you, try out this option. This may help issues with NFS and machines in VirtualBox, WSL, Containers, or Docker. In those cases, use a polling interval and ignore large folders like /node_modules/ to keep CPU usage minimal.
